---
- name: Install PHP-FPM
  apt: pkg={{ item }} state=present
  with_items:
    - php5-fpm
    - php5-cli
    - php5-curl
    - php5-gd
    - php5-mcrypt
    - php5-mysqlnd
    - php5-xsl
    - php5-xdebug
    - php5-geoip
    - php5-imagick
    - php5-memcache
    - php5-memcached
    - libpuzzle-php
- name: Remove default pool
  file: path=/etc/php5/fpm/pool.d/www.conf state=absent
