---
- name: Nginx config
  template: src=silexerrorhandling.local.j2 dest=/etc/nginx/sites-available/silexerrorhandling.local
  notify: restart nginx
- name: Wlaczenie konfiguracji nginxa
  file: src=/etc/nginx/sites-available/silexerrorhandling.local dest=/etc/nginx/sites-enabled/silexerrorhandling.local state=link
  notify: restart nginx
- name: Add entry to /etc/hosts
  lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1 silexerrorhandling\.local' line='127.0.0.1 silexerrorhandling.local' owner=root group=root mode=0644
- name: Create error log
  command: touch /var/log/php.silexerrorhandling.error.log creates=/var/log/php.silexerrorhandling.error.log
- name: Error log permissions
  command: chmod 777 /var/log/php.silexerrorhandling.error.log
- name: Configure PHP-FPM
  template: src=silexerrorhandling.conf.j2 dest=/etc/php5/fpm/pool.d/silexerrorhandling.conf
  notify: restart php-fpm
- name: Create /var/www dir
  file: dest=/var/www state=directory owner=www-data group=www-data mode=0755
- name: Create symlink to /var/www/silexerrorhandling
  file: src=/vagrant dest=/var/www/silexerrorhandling state=link
